[package]
name = "test-actix-mongo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "*"
actix-web = "4.0.0-beta.5"
serde = "1.0.132"
serde_json = "1.0"
tokio = "*"
actix-rt = "*"